name: Audit for known vulnerabilities in Python dependencies
on:
  push:
    branches:
      - trivy-scanning
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '31 15 * * 1'

jobs:
  pip_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: .
